import * as hmUI from '@zos/ui'
import { px } from '@zos/utils'
import { getText } from '@zos/i18n'
import { localStorage } from '@zos/storage'
import { setPageBrightTime, resetPageBrightTime, pauseDropWristScreenOff, resetDropWristScreenOff } from '@zos/display'
import { onGesture, offGesture, onKey, offKey, GESTURE_RIGHT, KEY_BACK, KEY_EVENT_CLICK } from '@zos/interaction'
import { Vibrator, VIBRATOR_SCENE_SHORT_STRONG, VIBRATOR_SCENE_DURATION } from '@zos/sensor'
import { BasePage } from '@zeppos/zml/base-page'

import {
  createEngine,
  TILE_COUNT,
  MAX_STRIKES,
  HIT_FLASH_MS,
  WARN_FRACTION,
  PHASE_COUNTDOWN,
  PHASE_RUNNING,
  PHASE_OVER,
} from '../../shared/engine.js'
import { REQ_SUBMIT, LOCAL_BEST } from '../../shared/protocol.js'
import { seconds, secondsLabel, grouped } from '../../shared/format.js'
import {
  CREAM,
  CREAM_DIM,
  CREAM_FAINT,
  ACCENT,
  SUCCESS,
  TILE_EMPTY,
  TILE_ACTIVE,
  TILE_WARN,
  TILE_HIT,
  PIP_SPENT,
  PIP_LEFT,
} from '../../shared/theme.js'
import {
  SCREEN_W,
  TILE,
  TILE_GAP,
  TILE_RADIUS,
  FRUIT,
  GRID_X,
  GRID_Y,
  GRID_W,
  GRID_H,
  tileX,
  tileY,
  tileInset,
  PIP_R,
  PIP_GAP,
  PIP_Y,
  CLOCK_Y,
  CLOCK_H,
  CLOCK_FONT,
  BODY_FONT,
  CAPTION_FONT,
  BIG_FONT,
} from '../../shared/layout.js'
import { ground, text, button, rect, circle, image, show, setText, setColor, setSrc } from '../../shared/widgets.js'

/** 25fps. Fast enough that a 460ms fruit gets a dozen frames; slow enough to stay cool. */
const TICK_MS = 40

/**
 * How long the page keeps the screen lit. Unlike the drop-wrist arm below, this is a page
 * *timeout* rather than a countdown from one moment, so it covers a visit of several runs
 * rather than one, and it is reset when the page is destroyed.
 */
const AWAKE_MS = 600000

const FRUIT_INSET = tileInset(FRUIT)

/** Generated by tools/generate_zepp_assets.py; 4px of nothing. */
const TAP_TARGET = 'tap.png'

const COUNTDOWN_FONT = px(96)
const RESULT_TITLE_Y = px(64)
const RESULT_SCORE_Y = px(112)
const RESULT_DETAIL_Y = px(192)
const RESULT_BEST_Y = px(228)
const RESULT_STATUS_Y = px(264)
const RESULT_BUTTON_Y = px(322)
const RESULT_BUTTON_X = px(80)

const TILE_STATE_EMPTY = 0
const TILE_STATE_ACTIVE = 1
const TILE_STATE_WARN = 2
const TILE_STATE_HIT = 3

const TILE_COLORS = [TILE_EMPTY, TILE_ACTIVE, TILE_WARN, TILE_HIT]

/**
 * The run.
 *
 * Rendering is a diff, not a redraw. Every widget on the board is created once in `build`
 * and then only ever has a property rewritten, and only when the value it is showing has
 * actually changed - so a quiet frame costs nine comparisons and no draw calls at all.
 * That matters more here than it would on a phone: this loop runs 25 times a second on a
 * watch, and a `createWidget`/`deleteWidget` pair per fruit would churn the heap on the
 * exact device that has the least of it.
 *
 * Touch is nine BUTTON widgets laid over the board, one per tile. The tidier-looking
 * alternative - a single listener on the background, mapping coordinates to a tile - does
 * not work: a `FILL_RECT` under the board never receives the tap at all (verified on a
 * T-Rex 3 Pro; the handler simply never fires). A BUTTON does, so the buttons sit on top,
 * drawing a 4px transparent bitmap so that nothing of them shows.
 *
 * They are a tile *pitch* wide rather than a tile wide, so together they tile the whole
 * grid with no dead gutter between them: a tap that lands between two tiles goes to the
 * nearer one instead of to nothing, which at five fruit a second is the difference
 * between a near miss and a strike.
 */

const engine = createEngine()
const vibrator = new Vibrator()

const view = {
  clock: null,
  pips: [],
  tiles: [],
  fruits: [],
  taps: [],
  countdown: null,
  result: {},
}

/** What each widget is currently showing, so a frame only writes what changed. */
const shown = {
  clockTenths: -1,
  strikes: -1,
  tileState: new Array(TILE_COUNT).fill(-1),
  fruit: new Array(TILE_COUNT).fill(null),
  countdown: -1,
}

let ticker = null
let submitted = false

/**
 * False once the page is gone. The score submission is a round trip through the phone and
 * its reply can land long after a back-swipe; a widget handle from a torn-down page still
 * passes the `if (widget)` check in `setText`, so the guard has to be explicit.
 */
let alive = false

Page(
  BasePage({
    build() {
      alive = true
      view.pips = []
      view.tiles = []
      view.fruits = []
      view.taps = []

      ground()

      buildHud()
      buildBoard(this)
      buildCountdown()
      buildResult(this)

      setPageBrightTime({ brightTime: AWAKE_MS })
      // `duration: 0` means "until resetDropWristScreenOff", which `onDestroy` already
      // calls. A finite duration would be a countdown from this moment rather than a
      // per-run guarantee: several runs and their result screens easily outlast one, and
      // the arm would lapse mid-run — the display blanking while the ticker keeps going,
      // so fruit expire unseen and the player is handed the result of a run they could
      // not watch.
      pauseDropWristScreenOff({ duration: 0 })

      // A run in progress swallows Back and ends the run instead; a second Back then
      // leaves, because by that point there is nothing to protect. The same rule for the
      // gesture and for the hardware button - a T-Rex has both, and a player who has just
      // lost a good run should not have to remember which one they used.
      onGesture({
        callback: (event) => (event === GESTURE_RIGHT ? this.onBack() : false),
      })
      onKey({
        callback: (key, keyEvent) =>
          key === KEY_BACK && keyEvent === KEY_EVENT_CLICK ? this.onBack() : false,
      })

      this.startRun()
    },

    onDestroy() {
      alive = false
      stopTicker()
      offGesture()
      offKey()
      resetPageBrightTime()
      resetDropWristScreenOff()
    },

    startRun() {
      submitted = false
      resetShown()
      showBoard(true)
      showResult(false)
      engine.start(Date.now())
      renderFrame(Date.now())
      stopTicker()
      ticker = setInterval(() => this.tick(), TICK_MS)
    },

    tick() {
      const now = Date.now()
      const strikesBefore = engine.strikes

      engine.update(now)

      if (engine.strikes > strikesBefore) {
        vibrator.setMode(VIBRATOR_SCENE_SHORT_STRONG)
        vibrator.start()
      }

      if (engine.phase === PHASE_OVER) {
        stopTicker()
        this.finish()
        return
      }

      renderFrame(now)
    },

    onTile(tile) {
      if (engine.phase !== PHASE_RUNNING) return
      const now = Date.now()
      if (engine.tap(tile, now)) renderFrame(now)
    },

    /**
     * True to swallow the gesture, which is what keeps a live run from being walked out
     * of by accident: the first Back ends the run and shows what it was worth, and only
     * the second one leaves. A run still on the countdown has nothing to protect, so it
     * lets that one through untouched.
     */
    onBack() {
      if (engine.phase !== PHASE_RUNNING) return false
      stopTicker()
      engine.quitRun(Date.now())
      this.finish()
      return true
    },

    finish() {
      const millis = engine.elapsedMs
      const hits = engine.hits

      const previousBest = Number(localStorage.getItem(LOCAL_BEST, 0)) || 0
      const isBest = millis > previousBest
      if (isBest) localStorage.setItem(LOCAL_BEST, millis)

      vibrator.setMode(VIBRATOR_SCENE_DURATION)
      vibrator.start()

      showBoard(false)
      showResult(true)

      setText(view.result.title, engine.quit ? getText('runEnded') : getText('whaaacked'))
      setText(view.result.score, secondsLabel(millis))
      setText(view.result.detail, grouped(millis) + getText('msAnd') + hits + getText('hits'))
      setText(
        view.result.best,
        isBest
          ? getText('newBest')
          : getText('best') + secondsLabel(Math.max(previousBest, millis)),
      )
      setColor(view.result.best, isBest ? SUCCESS : CREAM_FAINT)

      this.submit(millis, hits)
    },

    /**
     * Records the run, once.
     *
     * A run that cannot be recorded is still a run: the score is already in local storage
     * and already on screen before this is called, so every outcome here is a line of
     * text rather than a failure. The three that matter are told apart on purpose - "sign
     * in on your phone" is advice a player can act on, "check your connection" is not
     * advice at all if the real answer was that the server refused the row.
     */
    submit(millis, hits) {
      if (submitted || millis <= 0) {
        if (millis <= 0) setText(view.result.status, '')
        return
      }
      submitted = true
      setText(view.result.status, getText('saving'))

      this.request({ method: REQ_SUBMIT, params: { millis, hits } })
        .then((data) => {
          if (!alive) return
          if (data && data.saved) {
            setText(view.result.status, getText('saved'))
            setColor(view.result.status, SUCCESS)
            return
          }
          const reason = data && data.reason
          setText(
            view.result.status,
            reason === 'signed_out'
              ? getText('signInToRank')
              : (data && data.message) || getText('notSaved'),
          )
          setColor(view.result.status, CREAM_FAINT)
        })
        .catch(() => {
          if (!alive) return
          setText(view.result.status, getText('phoneUnreachable'))
          setColor(view.result.status, CREAM_FAINT)
        })
    },
  }),
)

// -------------------------------------------------------------------------- building

function buildHud() {
  const centre = Math.round(SCREEN_W / 2)
  for (let i = 0; i < MAX_STRIKES; i++) {
    view.pips.push(
      circle({
        cx: centre + (i - 1) * PIP_GAP,
        cy: PIP_Y,
        r: PIP_R,
        color: PIP_LEFT,
      }),
    )
  }

  view.clock = text({
    y: CLOCK_Y,
    h: CLOCK_H,
    size: CLOCK_FONT,
    color: CREAM,
    content: '0.0',
  })
}

function buildBoard(page) {
  for (let i = 0; i < TILE_COUNT; i++) {
    view.tiles.push(
      rect({
        x: tileX(i),
        y: tileY(i),
        w: TILE,
        h: TILE,
        color: TILE_EMPTY,
        radius: TILE_RADIUS,
      }),
    )
  }
  // Every fruit widget is created up front and then only ever has its source swapped.
  // Nine of them is the ceiling however many slots the ladder opens, because two fruit
  // can never share a tile.
  for (let i = 0; i < TILE_COUNT; i++) {
    const fruit = image({
      x: tileX(i) + FRUIT_INSET,
      y: tileY(i) + FRUIT_INSET,
      w: FRUIT,
      h: FRUIT,
      src: 'fruit-apple.png',
    })
    show(fruit, false)
    view.fruits.push(fruit)
  }
  // Last, so they are on top of everything they cover.
  for (let i = 0; i < TILE_COUNT; i++) {
    view.taps.push(
      hmUI.createWidget(hmUI.widget.BUTTON, {
        x: tileX(i) - Math.round(TILE_GAP / 2),
        y: tileY(i) - Math.round(TILE_GAP / 2),
        w: TILE + TILE_GAP,
        h: TILE + TILE_GAP,
        normal_src: TAP_TARGET,
        press_src: TAP_TARGET,
        click_func: () => page.onTile(i),
      }),
    )
  }
}

function buildCountdown() {
  view.countdown = text({
    x: GRID_X,
    y: GRID_Y + Math.round((GRID_H - COUNTDOWN_FONT) / 2),
    w: GRID_W,
    h: COUNTDOWN_FONT,
    size: COUNTDOWN_FONT,
    color: ACCENT,
    content: '',
  })
}

function buildResult(page) {
  view.result.title = text({
    y: RESULT_TITLE_Y,
    h: BODY_FONT + px(16),
    size: px(34),
    color: ACCENT,
    content: '',
  })
  view.result.score = text({
    y: RESULT_SCORE_Y,
    h: BIG_FONT + px(12),
    size: BIG_FONT,
    color: CREAM,
    content: '',
  })
  view.result.detail = text({
    y: RESULT_DETAIL_Y,
    h: CAPTION_FONT + px(10),
    size: CAPTION_FONT,
    color: CREAM_DIM,
    content: '',
  })
  view.result.best = text({
    y: RESULT_BEST_Y,
    h: CAPTION_FONT + px(10),
    size: CAPTION_FONT,
    color: CREAM_FAINT,
    content: '',
  })
  view.result.status = text({
    x: RESULT_BUTTON_X,
    y: RESULT_STATUS_Y,
    w: SCREEN_W - RESULT_BUTTON_X * 2,
    h: CAPTION_FONT * 2 + px(8),
    size: CAPTION_FONT,
    color: CREAM_FAINT,
    content: '',
    wrap: true,
  })
  view.result.again = button({
    x: RESULT_BUTTON_X,
    y: RESULT_BUTTON_Y,
    w: SCREEN_W - RESULT_BUTTON_X * 2,
    h: px(70),
    label: getText('playAgain'),
    primary: true,
    onClick: () => page.startRun(),
  })
  showResult(false)
}

// ------------------------------------------------------------------------- rendering

function resetShown() {
  shown.clockTenths = -1
  shown.strikes = -1
  shown.countdown = -1
  for (let i = 0; i < TILE_COUNT; i++) {
    shown.tileState[i] = -1
    shown.fruit[i] = null
  }
}

function showBoard(visible) {
  show(view.clock, visible)
  for (let i = 0; i < view.pips.length; i++) show(view.pips[i], visible)
  for (let i = 0; i < TILE_COUNT; i++) {
    show(view.tiles[i], visible)
    show(view.taps[i], visible)
    if (!visible) show(view.fruits[i], false)
  }
  if (!visible) show(view.countdown, false)
}

function showResult(visible) {
  show(view.result.title, visible)
  show(view.result.score, visible)
  show(view.result.detail, visible)
  show(view.result.best, visible)
  show(view.result.status, visible)
  show(view.result.again, visible)
}

function renderFrame(now) {
  if (engine.phase === PHASE_COUNTDOWN) {
    if (shown.countdown !== engine.countdownValue) {
      shown.countdown = engine.countdownValue
      setText(view.countdown, engine.countdownValue > 0 ? String(engine.countdownValue) : '')
      show(view.countdown, engine.countdownValue > 0)
    }
  } else if (shown.countdown !== -1) {
    shown.countdown = -1
    show(view.countdown, false)
  }

  // A tenth of a second is the smallest step the readout shows, so anything finer is a
  // property write nobody can see.
  const tenths = Math.floor(engine.elapsedMs / 100)
  if (tenths !== shown.clockTenths) {
    shown.clockTenths = tenths
    setText(view.clock, seconds(engine.elapsedMs))
  }

  if (engine.strikes !== shown.strikes) {
    shown.strikes = engine.strikes
    for (let i = 0; i < view.pips.length; i++) {
      setColor(view.pips[i], i < engine.strikes ? PIP_SPENT : PIP_LEFT)
    }
  }

  for (let tile = 0; tile < TILE_COUNT; tile++) {
    const active = engine.fruitAt(tile)

    let state = TILE_STATE_EMPTY
    if (active) {
      state =
        engine.remainingFraction(active, now) <= WARN_FRACTION
          ? TILE_STATE_WARN
          : TILE_STATE_ACTIVE
    } else if (now - engine.clearedAt[tile] < HIT_FLASH_MS) {
      state = TILE_STATE_HIT
    }

    if (state !== shown.tileState[tile]) {
      shown.tileState[tile] = state
      setColor(view.tiles[tile], TILE_COLORS[state])
    }

    const fruit = active ? active.fruit : null
    if (fruit !== shown.fruit[tile]) {
      shown.fruit[tile] = fruit
      if (fruit) {
        setSrc(view.fruits[tile], 'fruit-' + fruit + '.png')
        show(view.fruits[tile], true)
      } else {
        show(view.fruits[tile], false)
      }
    }
  }
}

function stopTicker() {
  if (ticker) {
    clearInterval(ticker)
    ticker = null
  }
}
