import * as hmUI from '@zos/ui'
import { px } from '@zos/utils'
import { getText } from '@zos/i18n'
import { localStorage } from '@zos/storage'
import { setPageBrightTime, resetPageBrightTime, pauseDropWristScreenOff, resetDropWristScreenOff } from '@zos/display'
import { onGesture, offGesture, onKey, offKey, GESTURE_RIGHT, KEY_BACK, KEY_EVENT_CLICK } from '@zos/interaction'
import { Vibrator, VIBRATOR_SCENE_SHORT_STRONG, VIBRATOR_SCENE_DURATION } from '@zos/sensor'
import { BasePage } from '@zeppos/zml/base-page'

import {
  createEngine,
  TILE_COUNT,
  MAX_STRIKES,
  SPLAT_LIFE_MS,
  SPLAT_HOLD,
  SURVIVE_TIERS,
  tiersCleared,
  WARN_FRACTION,
  PHASE_COUNTDOWN,
  PHASE_RUNNING,
  PHASE_OVER,
} from '../../shared/engine.js'
import { REQ_SUBMIT, LOCAL_BEST } from '../../shared/protocol.js'
import { seconds, secondsLabel } from '../../shared/format.js'
import { startMusic, primeSplat, playSplat, release as releaseAudio } from '../../shared/audio.js'
import {
  CREAM,
  CREAM_DIM,
  CREAM_FAINT,
  ACCENT,
  SUCCESS,
  TILE_EMPTY,
  TILE_ACTIVE,
  TILE_WARN,
  PIP_SPENT,
  PIP_LEFT,
} from '../../shared/theme.js'
import {
  SCREEN_W,
  TILE,
  TILE_GAP,
  TILE_RADIUS,
  FRUIT,
  SPLAT,
  BADGE,
  BADGE_GAP,
  GRID_X,
  GRID_Y,
  GRID_W,
  GRID_H,
  tileX,
  tileY,
  tileInset,
  splatX,
  splatY,
  PIP_R,
  PIP_GAP,
  PIP_Y,
  CLOCK_Y,
  CLOCK_H,
  CLOCK_FONT,
  BODY_FONT,
  CAPTION_FONT,
  BIG_FONT,
} from '../../shared/layout.js'
import {
  ground,
  text,
  button,
  rect,
  circle,
  image,
  show,
  setText,
  setColor,
  setSrc,
  setAlpha,
  setX,
} from '../../shared/widgets.js'

/** 25fps. Fast enough that a 460ms fruit gets a dozen frames; slow enough to stay cool. */
const TICK_MS = 40

/**
 * How long the page keeps the screen lit. Unlike the drop-wrist arm below, this is a page
 * *timeout* rather than a countdown from one moment, so it covers a visit of several runs
 * rather than one, and it is reset when the page is destroyed.
 */
const AWAKE_MS = 600000

const FRUIT_INSET = tileInset(FRUIT)

/** Generated by tools/generate_zepp_assets.py; 4px of nothing. */
const TAP_TARGET = 'tap.png'

const COUNTDOWN_FONT = px(96)

/**
 * The result screen, top to bottom.
 *
 * Tighter than it was, to fit the badge row in. What went to make room was the raw
 * millisecond count: it said the same thing as the seconds above it, in a unit nobody
 * compares runs in, and the hits it shared a line with have moved up next to the best.
 * The bottom is set by the glass rather than by taste - the Play again button ends at
 * y=412, where its far corner is 235px from the centre and the rim is at 240.
 */
const RESULT_TITLE_Y = px(58)
const RESULT_SCORE_Y = px(106)
const BADGE_Y = px(188)
const RESULT_BEST_Y = px(244)
const RESULT_STATUS_Y = px(282)
const RESULT_BUTTON_Y = px(342)
const RESULT_BUTTON_X = px(80)

/** Four tiers plus the trophy: the most badges a single run can earn. */
const BADGE_SLOTS = SURVIVE_TIERS.length + 1

const TILE_STATE_EMPTY = 0
const TILE_STATE_ACTIVE = 1
const TILE_STATE_WARN = 2

const TILE_COLORS = [TILE_EMPTY, TILE_ACTIVE, TILE_WARN]

/** Where the fade begins, in milliseconds rather than as a fraction, once per module. */
const SPLAT_HOLD_MS = SPLAT_LIFE_MS * SPLAT_HOLD

/**
 * The run.
 *
 * Rendering is a diff, not a redraw. Every widget on the board is created once in `build`
 * and then only ever has a property rewritten, and only when the value it is showing has
 * actually changed - so a quiet frame costs nine comparisons and no draw calls at all.
 * That matters more here than it would on a phone: this loop runs 25 times a second on a
 * watch, and a `createWidget`/`deleteWidget` pair per fruit would churn the heap on the
 * exact device that has the least of it.
 *
 * The board is four layers, and the order they are created in is the order they stack:
 * tiles, then splats, then fruit, then the touch targets. That is what puts a fresh fruit
 * over the splat of the one whacked before it, and lets a splat spill across the gutter
 * onto its neighbours without covering what is growing there.
 *
 * A splat is one widget per tile rather than one per hit, because the engine keeps one
 * splat per tile for the same reason: a widget shows one bitmap, so a second hit on a
 * tile that is still fading replaces what is on it. At five hits a second across nine
 * tiles that is the difference between nine widgets and a hundred.
 *
 * Touch is nine BUTTON widgets laid over the board, one per tile. The tidier-looking
 * alternative - a single listener on the background, mapping coordinates to a tile - does
 * not work: a `FILL_RECT` under the board never receives the tap at all (verified on a
 * T-Rex 3 Pro; the handler simply never fires). A BUTTON does, so the buttons sit on top,
 * drawing a 4px transparent bitmap so that nothing of them shows.
 *
 * They are a tile *pitch* wide rather than a tile wide, so together they tile the whole
 * grid with no dead gutter between them: a tap that lands between two tiles goes to the
 * nearer one instead of to nothing, which at five fruit a second is the difference
 * between a near miss and a strike.
 */

const engine = createEngine()
const vibrator = new Vibrator()

const view = {
  clock: null,
  pips: [],
  tiles: [],
  splats: [],
  fruits: [],
  taps: [],
  countdown: null,
  result: {},
  badges: [],
}

/** What each widget is currently showing, so a frame only writes what changed. */
const shown = {
  clockTenths: -1,
  strikes: -1,
  tileState: new Array(TILE_COUNT).fill(-1),
  fruit: new Array(TILE_COUNT).fill(null),
  splat: new Array(TILE_COUNT).fill(null),
  splatAlpha: new Array(TILE_COUNT).fill(-1),
  countdown: -1,
}

let ticker = null
let submitted = false

/**
 * False once the page is gone. The score submission is a round trip through the phone and
 * its reply can land long after a back-swipe; a widget handle from a torn-down page still
 * passes the `if (widget)` check in `setText`, so the guard has to be explicit.
 */
let alive = false

Page(
  BasePage({
    build() {
      alive = true
      view.pips = []
      view.tiles = []
      view.splats = []
      view.fruits = []
      view.taps = []
      view.badges = []

      ground()

      buildHud()
      buildBoard(this)
      buildCountdown()
      buildResult(this)

      setPageBrightTime({ brightTime: AWAKE_MS })
      // `duration: 0` means "until resetDropWristScreenOff", which `onDestroy` already
      // calls. A finite duration would be a countdown from this moment rather than a
      // per-run guarantee: several runs and their result screens easily outlast one, and
      // the arm would lapse mid-run — the display blanking while the ticker keeps going,
      // so fruit expire unseen and the player is handed the result of a run they could
      // not watch.
      pauseDropWristScreenOff({ duration: 0 })

      // Both are asynchronous and neither is worth waiting for: the splat is loaded now
      // so that the first hit of the first run plays as promptly as the last, and the
      // music starts whenever it is ready. Started here rather than in `startRun` because
      // the music is meant to carry across the result screen and into the next run - a
      // track that stopped and restarted every time somebody pressed Play again would be
      // a stutter, not a soundtrack.
      //
      // The splat goes first because a watch may only hand out one player, and if it
      // does, the sound worth spending it on is the one that answers a tap.
      primeSplat()
      startMusic()

      // A run in progress swallows Back and ends the run instead; a second Back then
      // leaves, because by that point there is nothing to protect. The same rule for the
      // gesture and for the hardware button - a T-Rex has both, and a player who has just
      // lost a good run should not have to remember which one they used.
      onGesture({
        callback: (event) => (event === GESTURE_RIGHT ? this.onBack() : false),
      })
      onKey({
        callback: (key, keyEvent) =>
          key === KEY_BACK && keyEvent === KEY_EVENT_CLICK ? this.onBack() : false,
      })

      this.startRun()
    },

    onDestroy() {
      alive = false
      stopTicker()
      offGesture()
      offKey()
      resetPageBrightTime()
      resetDropWristScreenOff()
      // The one call that has to happen. A player left holding the audio route keeps the
      // music going into whatever the watch shows next, and keeps the speaker powered.
      releaseAudio()
    },

    startRun() {
      submitted = false
      resetShown()
      showBoard(true)
      showResult(false)
      engine.start(Date.now())
      renderFrame(Date.now())
      stopTicker()
      ticker = setInterval(() => this.tick(), TICK_MS)
    },

    tick() {
      const now = Date.now()
      const strikesBefore = engine.strikes

      engine.update(now)

      if (engine.strikes > strikesBefore) {
        vibrator.setMode(VIBRATOR_SCENE_SHORT_STRONG)
        vibrator.start()
      }

      if (engine.phase === PHASE_OVER) {
        stopTicker()
        this.finish()
        return
      }

      renderFrame(now)
    },

    onTile(tile) {
      if (engine.phase !== PHASE_RUNNING) return
      const now = Date.now()
      if (!engine.tap(tile, now)) return
      // Rendered before the sound, because the splat is the feedback that has to be
      // immediate: `playSplat` is a call into the media stack and a miss there must not
      // hold up the frame that shows the hit landed.
      renderFrame(now)
      playSplat(now)
    },

    /**
     * True to swallow the gesture, which is what keeps a live run from being walked out
     * of by accident: the first Back ends the run and shows what it was worth, and only
     * the second one leaves. A run still on the countdown has nothing to protect, so it
     * lets that one through untouched.
     */
    onBack() {
      if (engine.phase !== PHASE_RUNNING) return false
      stopTicker()
      engine.quitRun(Date.now())
      this.finish()
      return true
    },

    finish() {
      const millis = engine.elapsedMs
      const hits = engine.hits

      const previousBest = Number(localStorage.getItem(LOCAL_BEST, 0)) || 0
      const isBest = millis > previousBest
      if (isBest) localStorage.setItem(LOCAL_BEST, millis)

      vibrator.setMode(VIBRATOR_SCENE_DURATION)
      vibrator.start()

      showBoard(false)
      showResult(true)

      setText(view.result.title, engine.quit ? getText('runEnded') : getText('whaaacked'))
      setText(view.result.score, secondsLabel(millis))
      setText(
        view.result.best,
        hits +
          getText('hits') +
          getText('sep') +
          (isBest
            ? getText('newBest')
            : getText('best') + secondsLabel(Math.max(previousBest, millis))),
      )
      setColor(view.result.best, isBest ? SUCCESS : CREAM_FAINT)

      // The trophy is for beating a run, not for having one. On a watch that has never
      // seen a finished run `previousBest` is zero, every score is a "best", and a trophy
      // for clearing nothing would be the first thing a new player was ever awarded - and
      // the last time it meant anything.
      showBadges(tiersCleared(millis), previousBest > 0 && millis > previousBest)

      this.submit(millis, hits)
    },

    /**
     * Records the run, once.
     *
     * A run that cannot be recorded is still a run: the score is already in local storage
     * and already on screen before this is called, so every outcome here is a line of
     * text rather than a failure. The three that matter are told apart on purpose - "sign
     * in on your phone" is advice a player can act on, "check your connection" is not
     * advice at all if the real answer was that the server refused the row.
     */
    submit(millis, hits) {
      // The colour is reset alongside every write, not only on the paths that set one.
      // These widgets are built once and reused by every later run on this visit, so the
      // green that meant "Saved to the board" at the end of one run is still on the widget
      // at the start of the next - and "Saving…" rendered in it says the run is already on
      // the board while the request is still on the wire.
      if (submitted || millis <= 0) {
        if (millis <= 0) {
          setText(view.result.status, '')
          setColor(view.result.status, CREAM_FAINT)
        }
        return
      }
      submitted = true
      setText(view.result.status, getText('saving'))
      setColor(view.result.status, CREAM_FAINT)

      this.request({ method: REQ_SUBMIT, params: { millis, hits } })
        .then((data) => {
          if (!alive) return
          if (data && data.saved) {
            setText(view.result.status, getText('saved'))
            setColor(view.result.status, SUCCESS)
            return
          }
          const reason = data && data.reason
          setText(
            view.result.status,
            reason === 'signed_out'
              ? getText('signInToRank')
              : (data && data.message) || getText('notSaved'),
          )
          setColor(view.result.status, CREAM_FAINT)
        })
        .catch(() => {
          if (!alive) return
          setText(view.result.status, getText('phoneUnreachable'))
          setColor(view.result.status, CREAM_FAINT)
        })
    },
  }),
)

// -------------------------------------------------------------------------- building

function buildHud() {
  const centre = Math.round(SCREEN_W / 2)
  for (let i = 0; i < MAX_STRIKES; i++) {
    view.pips.push(
      circle({
        cx: centre + (i - 1) * PIP_GAP,
        cy: PIP_Y,
        r: PIP_R,
        color: PIP_LEFT,
      }),
    )
  }

  view.clock = text({
    y: CLOCK_Y,
    h: CLOCK_H,
    size: CLOCK_FONT,
    color: CREAM,
    content: '0.0',
  })
}

function buildBoard(page) {
  for (let i = 0; i < TILE_COUNT; i++) {
    view.tiles.push(
      rect({
        x: tileX(i),
        y: tileY(i),
        w: TILE,
        h: TILE,
        color: TILE_EMPTY,
        radius: TILE_RADIUS,
      }),
    )
  }
  // Over the tiles and under the fruit. Nine of them, one per tile, each holding whatever
  // was last whacked there for as long as it takes to fade.
  for (let i = 0; i < TILE_COUNT; i++) {
    const splat = image({
      x: splatX(i),
      y: splatY(i),
      w: SPLAT,
      h: SPLAT,
      src: 'splat-apple-0.png',
    })
    show(splat, false)
    view.splats.push(splat)
  }
  // Every fruit widget is created up front and then only ever has its source swapped.
  // Nine of them is the ceiling however many slots the ladder opens, because two fruit
  // can never share a tile.
  for (let i = 0; i < TILE_COUNT; i++) {
    const fruit = image({
      x: tileX(i) + FRUIT_INSET,
      y: tileY(i) + FRUIT_INSET,
      w: FRUIT,
      h: FRUIT,
      src: 'fruit-apple.png',
    })
    show(fruit, false)
    view.fruits.push(fruit)
  }
  // Last, so they are on top of everything they cover.
  for (let i = 0; i < TILE_COUNT; i++) {
    view.taps.push(
      hmUI.createWidget(hmUI.widget.BUTTON, {
        x: tileX(i) - Math.round(TILE_GAP / 2),
        y: tileY(i) - Math.round(TILE_GAP / 2),
        w: TILE + TILE_GAP,
        h: TILE + TILE_GAP,
        normal_src: TAP_TARGET,
        press_src: TAP_TARGET,
        click_func: () => page.onTile(i),
      }),
    )
  }
}

function buildCountdown() {
  view.countdown = text({
    x: GRID_X,
    y: GRID_Y + Math.round((GRID_H - COUNTDOWN_FONT) / 2),
    w: GRID_W,
    h: COUNTDOWN_FONT,
    size: COUNTDOWN_FONT,
    color: ACCENT,
    content: '',
  })
}

function buildResult(page) {
  view.result.title = text({
    y: RESULT_TITLE_Y,
    h: BODY_FONT + px(16),
    size: px(34),
    color: ACCENT,
    content: '',
  })
  view.result.score = text({
    y: RESULT_SCORE_Y,
    h: BIG_FONT + px(12),
    size: BIG_FONT,
    color: CREAM,
    content: '',
  })
  // Over the badge row, so a badge is never clipped by a text box drawn after it. Five
  // slots created once and moved rather than created per run: the row is centred, so
  // every widget's x depends on how many earned it, and a `createWidget` per result would
  // churn the heap on the device with the least of it.
  for (let i = 0; i < BADGE_SLOTS; i++) {
    const badge = image({
      x: 0,
      y: BADGE_Y,
      w: BADGE,
      h: BADGE,
      src: 'badge-best.png',
    })
    show(badge, false)
    view.badges.push(badge)
  }

  view.result.best = text({
    y: RESULT_BEST_Y,
    h: CAPTION_FONT + px(10),
    size: CAPTION_FONT,
    color: CREAM_FAINT,
    content: '',
  })
  view.result.status = text({
    x: RESULT_BUTTON_X,
    y: RESULT_STATUS_Y,
    w: SCREEN_W - RESULT_BUTTON_X * 2,
    h: CAPTION_FONT * 2 + px(8),
    size: CAPTION_FONT,
    color: CREAM_FAINT,
    content: '',
    wrap: true,
  })
  view.result.again = button({
    x: RESULT_BUTTON_X,
    y: RESULT_BUTTON_Y,
    w: SCREEN_W - RESULT_BUTTON_X * 2,
    h: px(70),
    label: getText('playAgain'),
    primary: true,
    onClick: () => page.startRun(),
  })
  showResult(false)
}

// ------------------------------------------------------------------------- rendering

function resetShown() {
  shown.clockTenths = -1
  shown.strikes = -1
  shown.countdown = -1
  for (let i = 0; i < TILE_COUNT; i++) {
    shown.tileState[i] = -1
    shown.fruit[i] = null
    shown.splat[i] = null
    shown.splatAlpha[i] = -1
  }
}

/**
 * A splat's opacity at `age`: full strength for the first stretch of its life, then a
 * linear fade to nothing. Same shape as the phone's, which holds and then fades rather
 * than fading throughout - a splat that starts dimming the instant it lands reads as a
 * mistake, where one that sits for a moment first reads as something that dried.
 */
function splatAlpha(age) {
  if (age <= SPLAT_HOLD_MS) return 255
  const left = 1 - (age - SPLAT_HOLD_MS) / (SPLAT_LIFE_MS - SPLAT_HOLD_MS)
  return Math.max(0, Math.round(left * 255))
}

function showBoard(visible) {
  show(view.clock, visible)
  for (let i = 0; i < view.pips.length; i++) show(view.pips[i], visible)
  for (let i = 0; i < TILE_COUNT; i++) {
    show(view.tiles[i], visible)
    show(view.taps[i], visible)
    if (!visible) {
      show(view.fruits[i], false)
      show(view.splats[i], false)
    }
  }
  if (!visible) show(view.countdown, false)
}

function showResult(visible) {
  show(view.result.title, visible)
  show(view.result.score, visible)
  show(view.result.best, visible)
  show(view.result.status, visible)
  show(view.result.again, visible)
  if (!visible) {
    for (let i = 0; i < view.badges.length; i++) show(view.badges[i], false)
  }
}

/**
 * Lays out what the run earned, centred as a row.
 *
 * Every tier cleared rather than only the highest, because the four read as a ladder -
 * the ring around each is a clock, a quarter lit at thirty seconds and closed at a
 * hundred and twenty - and a ladder with only its top rung showing is just a picture.
 * Seeing three of them fill up is most of the reward for a long run.
 */
function showBadges(tiers, beatenBest) {
  const names = []
  for (let i = 0; i < tiers.length; i++) names.push('badge-' + tiers[i] / 1000 + '.png')
  if (beatenBest) names.push('badge-best.png')

  const width = names.length * BADGE + Math.max(0, names.length - 1) * BADGE_GAP
  let x = Math.round((SCREEN_W - width) / 2)

  for (let i = 0; i < view.badges.length; i++) {
    if (i >= names.length) {
      show(view.badges[i], false)
      continue
    }
    setSrc(view.badges[i], names[i])
    setX(view.badges[i], x)
    show(view.badges[i], true)
    x += BADGE + BADGE_GAP
  }
}

function renderFrame(now) {
  if (engine.phase === PHASE_COUNTDOWN) {
    if (shown.countdown !== engine.countdownValue) {
      shown.countdown = engine.countdownValue
      setText(view.countdown, engine.countdownValue > 0 ? String(engine.countdownValue) : '')
      show(view.countdown, engine.countdownValue > 0)
    }
  } else if (shown.countdown !== -1) {
    shown.countdown = -1
    show(view.countdown, false)
  }

  // A tenth of a second is the smallest step the readout shows, so anything finer is a
  // property write nobody can see.
  const tenths = Math.floor(engine.elapsedMs / 100)
  if (tenths !== shown.clockTenths) {
    shown.clockTenths = tenths
    setText(view.clock, seconds(engine.elapsedMs))
  }

  if (engine.strikes !== shown.strikes) {
    shown.strikes = engine.strikes
    for (let i = 0; i < view.pips.length; i++) {
      setColor(view.pips[i], i < engine.strikes ? PIP_SPENT : PIP_LEFT)
    }
  }

  for (let tile = 0; tile < TILE_COUNT; tile++) {
    const active = engine.fruitAt(tile)

    let state = TILE_STATE_EMPTY
    if (active) {
      state =
        engine.remainingFraction(active, now) <= WARN_FRACTION
          ? TILE_STATE_WARN
          : TILE_STATE_ACTIVE
    }

    if (state !== shown.tileState[tile]) {
      shown.tileState[tile] = state
      setColor(view.tiles[tile], TILE_COLORS[state])
    }

    renderSplat(tile, now)

    const fruit = active ? active.fruit : null
    if (fruit !== shown.fruit[tile]) {
      shown.fruit[tile] = fruit
      if (fruit) {
        setSrc(view.fruits[tile], 'fruit-' + fruit + '.png')
        show(view.fruits[tile], true)
      } else {
        show(view.fruits[tile], false)
      }
    }
  }
}

/**
 * One tile's splat: swapped in when it lands, faded across its life, hidden when it is
 * gone.
 *
 * The alpha is written before the widget is shown, so a splat landing on a tile whose
 * last one had faded to nothing cannot appear for a frame at that leftover opacity.
 */
function renderSplat(tile, now) {
  const splat = engine.splats[tile]
  const widget = view.splats[tile]
  const src = splat ? 'splat-' + splat.fruit + '-' + splat.variant + '.png' : null

  if (src !== shown.splat[tile]) {
    shown.splat[tile] = src
    if (!src) {
      shown.splatAlpha[tile] = -1
      show(widget, false)
      return
    }
    shown.splatAlpha[tile] = splatAlpha(now - splat.bornMs)
    setSrc(widget, src)
    setAlpha(widget, shown.splatAlpha[tile])
    show(widget, true)
    return
  }

  if (!src) return
  const alpha = splatAlpha(now - splat.bornMs)
  if (alpha !== shown.splatAlpha[tile]) {
    shown.splatAlpha[tile] = alpha
    setAlpha(widget, alpha)
  }
}

function stopTicker() {
  if (ticker) {
    clearInterval(ticker)
    ticker = null
  }
}
