"""Generate zeppos/shared/secrets.js from local.properties.

    python tools/sync_zepp_secrets.py

The Zepp OS build has no equivalent of Gradle's BuildConfig: whatever the watch app needs
has to be a module it can import. So the same two values the Android build reads out of
`local.properties` are written into a small generated module, which `.gitignore` covers
for the reason `local.properties` gives - the anon key is a public client key, but keeping
it out of git means rotating it does not mean rewriting history.

Run this once after cloning, and again whenever the project's keys change.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "local.properties"
DEST = ROOT / "zeppos" / "shared" / "secrets.js"

NEEDED = ("SUPABASE_URL", "SUPABASE_ANON_KEY")

BANNER = """\
// Generated by tools/sync_zepp_secrets.py from local.properties. Do not edit, and do not
// commit: see shared/secrets.example.js for what this file is and why it is not in git.
"""


def read_properties(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def as_js_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def main() -> int:
    if not SOURCE.exists():
        print(f"{SOURCE} not found - see docs/SETUP.md", file=sys.stderr)
        return 1

    props = read_properties(SOURCE)
    missing = [key for key in NEEDED if not props.get(key)]
    if missing:
        print(f"local.properties is missing: {', '.join(missing)}", file=sys.stderr)
        return 1

    body = BANNER + "\n" + "".join(
        f"export const {key} = {as_js_string(props[key])}\n" for key in NEEDED
    )
    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(body, encoding="utf-8")

    host = props["SUPABASE_URL"].split("//")[-1]
    print(f"wrote {DEST.relative_to(ROOT)} -> {host}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
